{{- if .Values.awsSecretsManager.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.awsSecretsManager.secretProviderClassName }}
  labels:
    {{- include "umami.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.awsSecretsManager.region | default "ap-southeast-1" | quote }}
    objects: |
      - objectName: {{ .Values.awsSecretsManager.awsSecretName | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: {{ .Values.awsSecretsManager.jmesPath.databaseUrlKey | default "DATABASE_URL" | quote }}
            objectAlias: "DATABASE_URL"
          - path: {{ .Values.awsSecretsManager.jmesPath.appSecretKey | default "APP_SECRET" | quote }}
            objectAlias: "APP_SECRET"
  secretObjects:
    - secretName: {{ include "umami.secretName" . }}
      type: Opaque
      data:
        - objectName: "DATABASE_URL"
          key: {{ .Values.database.secretKeys.databaseUrl | default "DATABASE_URL" }}
        - objectName: "APP_SECRET"
          key: {{ .Values.database.secretKeys.appSecret | default "APP_SECRET" }}
{{- end }}
