{{- if and (not .Values.database.existingSecret) (not .Values.awsSecretsManager.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "umami.secretName" . }}
  labels:
    {{- include "umami.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.secretKeys.databaseUrl | default "DATABASE_URL" }}: {{ .Values.database.url | quote }}
  {{ .Values.database.secretKeys.appSecret | default "APP_SECRET" }}: {{ .Values.database.appSecret | quote }}
{{- end }}
